# Generated by Django 3.1.7 on 2021-04-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('stars_given', models.PositiveIntegerField()),
                ('dropdown', models.CharField(choices=[('Everyone', 'Yes'), ('Student/s', 'No')], max_length=9)),
                ('student1', models.CharField(blank=True, max_length=50)),
                ('student2', models.CharField(blank=True, max_length=50)),
                ('student3', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CreateQuestboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('required_stars', models.PositiveIntegerField()),
            ],
        ),
    ]
