# Generated by Django 3.1.7 on 2021-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquest',
            name='dropdown',
            field=models.CharField(choices=[('Everyone', 'Yes'), ('Student/s', 'No')], max_length=9, verbose_name='For everyone?'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 1:'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 2:'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 3:'),
        ),
    ]
