# Generated by Django 3.1.7 on 2021-04-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquest',
            name='questboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questboard.createquestboard'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='dropdown',
            field=models.CharField(choices=[('Everyone', 'Yes'), ('Student/s', 'No')], max_length=9, verbose_name='For everyone?'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 1:'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 2:'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='student3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Student 3:'),
        ),
        migrations.AlterField(
            model_name='createquestboard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createquestboard',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
