# Generated by Django 3.1.7 on 2021-04-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0003_auto_20210405_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questboard',
            new_name='CreateQuestboard',
        ),
    ]
