# Generated by Django 3.1.7 on 2021-04-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0003_auto_20210412_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquest',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='dropdown',
            field=models.CharField(choices=[('Everyone', 'Yes'), ('Student/s', 'No')], max_length=9, verbose_name='For everyone?'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='createquestboard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createquestboard',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
