# Generated by Django 3.2 on 2021-04-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0004_auto_20210409_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('stars_given', models.PositiveIntegerField()),
                ('dropdown', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questboard.createquestboard')),
            ],
        ),
    ]
