# Generated by Django 3.1.7 on 2021-04-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0004_auto_20210412_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquest',
            name='questboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questboard.createquestboard'),
        ),
        migrations.AlterField(
            model_name='createquest',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createquestboard',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
