# Generated by Django 3.1.7 on 2021-04-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0005_auto_20210412_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquestboard',
            name='hi',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
