# Generated by Django 3.1.7 on 2021-04-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0007_remove_createquestboard_hi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquest',
            name='questboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questboard.createquestboard'),
        ),
    ]
