# Generated by Django 3.1.7 on 2021-04-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0008_auto_20210412_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createquest',
            old_name='questboard',
            new_name='createquestboard',
        ),
    ]
